language: node_js
node_js:
  - "stable"

script:
  - yarn install
  - yarn test
  - yarn build

deploy:
  provider: surge
  cleanup: true
  project: ./build/
  domain: quizapp-typescript.surge.sh
  on:
    branch: master